quadrotor:
  quadrotor_propeller_1_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: propeller_1_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  quadrotor_propeller_2_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: propeller_2_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  quadrotor_propeller_3_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: propeller_3_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  quadrotor_propeller_4_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: propeller_4_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  quadrotor_camera_pitch_controller:
    type: position_controllers/JointPositionController
    joint: camera_pitch_joint
    pid: {p: 100.0, i: 0.0, d: 2.0}

  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: left_slide_joint
    pid: {p: 10.0, i: 0.0005, d: 0.2}

  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: right_slide_joint
    pid: {p: 10.0, i: 0.0005, d: 0.2}

  # left_finger_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: left_slide_joint
  #   pid: {p: 25.0, i: 0.0, d: 0.8}

  # right_finger_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: right_slide_joint
  #   pid: {p: 25.0, i: 0.0, d: 0.8}