quadrotor:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  rotor1_controller:
    type: effort_controllers/JointVelocityController
    joint: rotor1
    pid: {p: 1.0, i: 0.0, d: 0.0}

  rotor2_controller:
    type: effort_controllers/JointVelocityController
    joint: rotor2
    pid: {p: 1.0, i: 0.0, d: 0.0}

  rotor3_controller:
    type: effort_controllers/JointVelocityController
    joint: rotor3
    pid: {p: 1.0, i: 0.0, d: 0.0}

  rotor4_controller:
    type: effort_controllers/JointVelocityController
    joint: rotor4
    pid: {p: 1.0, i: 0.0, d: 0.0}

  # gazebo_ros_control:
  #   pid_gains:
  #     rotor1: {p: 0.1, i: 0.0, d: 0.0}
  #     rotor2: {p: 0.1, i: 0.0, d: 0.0}
  #     rotor3: {p: 0.1, i: 0.0, d: 0.0}
  #     rotor4: {p: 0.1, i: 0.0, d: 0.0}